### ISSUE TITLE
FIXED

### ISSUE THREAD

**Issue by AndryLavandery** [miladmorris/Edu-Mail-Generator-master#1]
I have already downloaded program, tried to start it and occured this error:

![image](https://user-images.githubusercontent.com/52602572/116538830-b8254600-a8f0-11eb-98e0-b0a8cbd2fde2.png)

**Comment by Andrewer001** [comment]
![image](https://user-images.githubusercontent.com/83415765/116574712-4956e580-a90e-11eb-88ce-50556392eb3e.png)

I am not connected to any proxy or VPN, just on my wifi.

**Comment by AndryLavandery** [comment]
> ![image](https://user-images.githubusercontent.com/83415765/116574712-4956e580-a90e-11eb-88ce-50556392eb3e.png)
> 
> I am not connected to any proxy or VPN, just on my wifi.

Does everything work for you?
You wanna say this happens by the reason of that I using VPN?

**Comment by Andrewer001** [comment]
Try it with firefox

**Comment by AndryLavandery** [comment]
> Try it with firefox

After install the FireFox I have new error..

Error - Message: Process unexpectedly closed with status 1

![image](https://user-images.githubusercontent.com/52602572/116578669-5083f080-a91a-11eb-95f2-e1bf45bbfb15.png)
